/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.iesiliberis.crudcentroeducativo.formularios;

import com.iesiliberis.crudcentroeducativo.controladorDAO.CursoAcademicoDaoImp;
import com.iesiliberis.crudcentroeducativo.entidades.CursoAcademico;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JRadioButtonMenuItem;

/**
 *
 * @author sergio
 */
public class frmMain extends javax.swing.JFrame {
    public int idCursoAcademico = 0;

    /**
     * Creates new form frmMain
     */
    public frmMain() throws SQLException {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        generaMenuCursoAcademico();
    }

    private void generaMenuCursoAcademico() throws SQLException{
        
        // Implementar dinamismo con la base de datos
        CursoAcademicoDaoImp cadi = CursoAcademicoDaoImp.getInstance();
        
        try {
            List<CursoAcademico> cursos = cadi.getAll();

            ButtonGroup bgrCursoAcademico=new ButtonGroup();

            JRadioButtonMenuItem jrbcurso;

            for (CursoAcademico ca : cursos) {
                jrbcurso = new JRadioButtonMenuItem(ca.getYearinicio()+"-"+ca.getYearfin(), true); 
                jMenuCursoAcademico.add(jrbcurso);
                
                if (idCursoAcademico == 0) {
                    idCursoAcademico=ca.getId();
                }
                bgrCursoAcademico.add(jrbcurso);
                
                jrbcurso.addItemListener(new ItemListener() {
                    
                    public void itemStateChanged(ItemEvent e) {
                    
                        JRadioButtonMenuItem jrbSelected = (JRadioButtonMenuItem)e.getItem();
                        idCursoAcademico = Integer.parseInt(jrbSelected.getName());
                        System.out.println(""+jrbSelected.getText());
                    }
                    
                });
            }
            
        } catch (Exception e) {
            System.out.println("Error: "+e.getMessage());
        }
        
    }
    
    private boolean existeFormulario(Object object){
    
        JInternalFrame[] frmcargados=pnldEscritorio.getAllFrames();
        
        for(int i=0;i<frmcargados.length;i++){ 
            System.out.println(""+frmcargados[i].getClass());
            if (frmcargados[i].getClass()==object.getClass()){
                return true;
            }
            
        }
        return false;
    }
    
    
    private boolean existeFormularioV2(String nombreclase){
    
        JInternalFrame[] frmcargados=pnldEscritorio.getAllFrames();
        
        for(int i=0;i<frmcargados.length;i++){ 
            
            if (frmcargados[i].getClass().equals(nombreclase)){
                return true;
            }
            
        }
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnldEscritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        optmCursoAcademico = new javax.swing.JMenuItem();
        optmCurso = new javax.swing.JMenuItem();
        optmAlumno = new javax.swing.JMenuItem();
        optmUnidad = new javax.swing.JMenuItem();
        optmAula = new javax.swing.JMenuItem();
        optmMatricula = new javax.swing.JMenuItem();
        optmAutorizaciones = new javax.swing.JMenuItem();
        jMenuCursoAcademico = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        optmAcerca = new javax.swing.JMenuItem();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Instrucciones");
        pnldEscritorio.add(jLabel1);
        jLabel1.setBounds(1170, 70, 110, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("En la pestaña mantenimiento seleccione");
        pnldEscritorio.add(jLabel2);
        jLabel2.setBounds(1050, 110, 340, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("el campo a editar/consultar");
        pnldEscritorio.add(jLabel3);
        jLabel3.setBounds(1050, 130, 280, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dentro en la tabla encontrará los datos");
        pnldEscritorio.add(jLabel4);
        jLabel4.setBounds(1050, 180, 340, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("de dicho campo");
        pnldEscritorio.add(jLabel5);
        jLabel5.setBounds(1050, 200, 220, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Añada, modifique o elimine lo que desee");
        pnldEscritorio.add(jLabel6);
        jLabel6.setBounds(1050, 250, 350, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("y aplique los cambios para que surjan efecto");
        pnldEscritorio.add(jLabel7);
        jLabel7.setBounds(1050, 270, 370, 20);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Parametrización");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Mantenimimientos");

        optmCursoAcademico.setMnemonic('t');
        optmCursoAcademico.setText("Curso Academico");
        optmCursoAcademico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optmCursoAcademicoMouseClicked(evt);
            }
        });
        optmCursoAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmCursoAcademicoActionPerformed(evt);
            }
        });
        editMenu.add(optmCursoAcademico);

        optmCurso.setMnemonic('y');
        optmCurso.setText("Curso");
        optmCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmCursoActionPerformed(evt);
            }
        });
        editMenu.add(optmCurso);

        optmAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        optmAlumno.setMnemonic('p');
        optmAlumno.setText("Alumno");
        optmAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmAlumnoActionPerformed(evt);
            }
        });
        editMenu.add(optmAlumno);

        optmUnidad.setText("Unidad");
        optmUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmUnidadActionPerformed(evt);
            }
        });
        editMenu.add(optmUnidad);

        optmAula.setText("Aula");
        optmAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmAulaActionPerformed(evt);
            }
        });
        editMenu.add(optmAula);

        optmMatricula.setText("Matricula");
        optmMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmMatriculaActionPerformed(evt);
            }
        });
        editMenu.add(optmMatricula);

        optmAutorizaciones.setText("Autorizaciones");
        optmAutorizaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmAutorizacionesActionPerformed(evt);
            }
        });
        editMenu.add(optmAutorizaciones);

        menuBar.add(editMenu);

        jMenuCursoAcademico.setText("Año Academico");
        menuBar.add(jMenuCursoAcademico);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        optmAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        optmAcerca.setMnemonic('a');
        optmAcerca.setText("Acerca de");
        optmAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmAcercaActionPerformed(evt);
            }
        });
        helpMenu.add(optmAcerca);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnldEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnldEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void optmAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmAcercaActionPerformed
        // TODO add your handling code here:
      frmAcercaDeDialogo frmacerca=new frmAcercaDeDialogo(this, rootPaneCheckingEnabled);
      frmacerca.setVisible(true);
        
    }//GEN-LAST:event_optmAcercaActionPerformed

    private void optmCursoAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmCursoAcademicoActionPerformed
        // TODO add your handling code here:
        //frmCursoAcademico frmcursoaca=new frmCursoAcademico();
        //frmcursoaca.show();
//setVisible(true);

        frmInternoCursoAcademico frmcursoaca=null;

        if (!existeFormulario(frmcursoaca)){
            frmcursoaca=new frmInternoCursoAcademico();
            pnldEscritorio.add(frmcursoaca);
            
            frmcursoaca.show();
                 
       }
    }//GEN-LAST:event_optmCursoAcademicoActionPerformed

    private void optmAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmAlumnoActionPerformed
        
        // TODO add your handling code here:
        
       frmInternoAlumnos frmalum=null;
       
       if (!existeFormulario(frmalum)){
            frmalum=new frmInternoAlumnos();
            pnldEscritorio.add(frmalum);
            frmalum.show();
                 
       }
       
              
    }//GEN-LAST:event_optmAlumnoActionPerformed

    private void optmCursoAcademicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optmCursoAcademicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_optmCursoAcademicoMouseClicked

    private void optmCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmCursoActionPerformed
        // TODO add your handling code here:
        frmInternoCurso form=null;
       
        if (!existeFormulario(form)){
            form=new frmInternoCurso();
            pnldEscritorio.add(form);
            form.show();         
        }
        
    }//GEN-LAST:event_optmCursoActionPerformed

    private void optmUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmUnidadActionPerformed
        // TODO add your handling code here:
        
        frmInternoUnidad form=null;
       
        if (!existeFormulario(form)){
            form=new frmInternoUnidad();
            pnldEscritorio.add(form);
            form.show();         
        }
    }//GEN-LAST:event_optmUnidadActionPerformed

    private void optmAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmAulaActionPerformed
        // TODO add your handling code here:
        
        frmInternoAula form=null;
       
        if (!existeFormulario(form)){
            form=new frmInternoAula();
            pnldEscritorio.add(form);
            form.show();         
        }
    }//GEN-LAST:event_optmAulaActionPerformed

    private void optmMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmMatriculaActionPerformed
        // TODO add your handling code here:
        
        frmInternoMatricula form=null;
       
        if (!existeFormulario(form)){
            form=new frmInternoMatricula();
            pnldEscritorio.add(form);
            form.show();         
        }
    }//GEN-LAST:event_optmMatriculaActionPerformed

    private void optmAutorizacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmAutorizacionesActionPerformed
        // TODO add your handling code here:
        frmInternoAutorizado form=null;
       
        if (!existeFormulario(form)){
            form=new frmInternoAutorizado();
            pnldEscritorio.add(form);
            form.show();         
        }
    }//GEN-LAST:event_optmAutorizacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmMain().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenuCursoAcademico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem optmAcerca;
    private javax.swing.JMenuItem optmAlumno;
    private javax.swing.JMenuItem optmAula;
    private javax.swing.JMenuItem optmAutorizaciones;
    private javax.swing.JMenuItem optmCurso;
    private javax.swing.JMenuItem optmCursoAcademico;
    private javax.swing.JMenuItem optmMatricula;
    private javax.swing.JMenuItem optmUnidad;
    private javax.swing.JDesktopPane pnldEscritorio;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
