/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.iesiliberis.crudcentroeducativo.formularios;

import com.iesiliberis.crudcentroeducativo.controladorDAO.CursoAcademicoDaoImp;
import com.iesiliberis.crudcentroeducativo.entidades.CursoAcademico;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JRadioButtonMenuItem;

/**
 *
 * @author sergio
 */
public class frmMain extends javax.swing.JFrame {
    public int idCursoAcademico = 0;

    /**
     * Creates new form frmMain
     */
    public frmMain() throws SQLException {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        generaMenuCursoAcademico();
    }

    private void generaMenuCursoAcademico() throws SQLException{
        
        // Implementar dinamismo con la base de datos
        CursoAcademicoDaoImp cadi = CursoAcademicoDaoImp.getInstance();
        
        try {
            List<CursoAcademico> cursos = cadi.getAll();

            ButtonGroup bgrCursoAcademico=new ButtonGroup();

            JRadioButtonMenuItem jrbcurso;

            for (CursoAcademico ca : cursos) {
                jrbcurso = new JRadioButtonMenuItem(ca.getYearinicio()+"-"+ca.getYearfin(), true); 
                jMenuCursoAcademico.add(jrbcurso);
                
                if (idCursoAcademico == 0) {
                    idCursoAcademico=ca.getId();
                }
                bgrCursoAcademico.add(jrbcurso);
                
                jrbcurso.addItemListener(new ItemListener() {
                    
                    public void itemStateChanged(ItemEvent e) {
                    
                        JRadioButtonMenuItem jrbSelected = (JRadioButtonMenuItem)e.getItem();
                        idCursoAcademico = Integer.parseInt(jrbSelected.getName());
                        System.out.println(""+jrbSelected.getText());
                    }
                    
                });
            }
            
        } catch (Exception e) {
            System.out.println("Error: "+e.getMessage());
        }
        
    }
    
    private boolean existeFormulario(Object object){
    
        JInternalFrame[] frmcargados=pnldEscritorio.getAllFrames();
        
        for(int i=0;i<frmcargados.length;i++){ 
            System.out.println(""+frmcargados[i].getClass());
            if (frmcargados[i].getClass()==object.getClass()){
                return true;
            }
            
        }
        return false;
    }
    
    
    private boolean existeFormularioV2(String nombreclase){
    
        JInternalFrame[] frmcargados=pnldEscritorio.getAllFrames();
        
        for(int i=0;i<frmcargados.length;i++){ 
            
            if (frmcargados[i].getClass().equals(nombreclase)){
                return true;
            }
            
        }
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnldEscritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        optmCursoAcademico = new javax.swing.JMenuItem();
        optmCurso = new javax.swing.JMenuItem();
        optmAlumno = new javax.swing.JMenuItem();
        optmUnidades = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuCursoAcademico = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        optmAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Parametrización");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Mantenimimientos");

        optmCursoAcademico.setMnemonic('t');
        optmCursoAcademico.setText("Curso Academico");
        optmCursoAcademico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optmCursoAcademicoMouseClicked(evt);
            }
        });
        optmCursoAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmCursoAcademicoActionPerformed(evt);
            }
        });
        editMenu.add(optmCursoAcademico);

        optmCurso.setMnemonic('y');
        optmCurso.setText("Curso");
        optmCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmCursoActionPerformed(evt);
            }
        });
        editMenu.add(optmCurso);

        optmAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        optmAlumno.setMnemonic('p');
        optmAlumno.setText("Alumno");
        optmAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmAlumnoActionPerformed(evt);
            }
        });
        editMenu.add(optmAlumno);

        optmUnidades.setText("Unidades");
        optmUnidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optmUnidadesMouseClicked(evt);
            }
        });

        jMenuItem1.setText("jMenuItem1");
        optmUnidades.add(jMenuItem1);

        editMenu.add(optmUnidades);

        menuBar.add(editMenu);

        jMenuCursoAcademico.setText("Año Academico");
        menuBar.add(jMenuCursoAcademico);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        optmAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        optmAcerca.setMnemonic('a');
        optmAcerca.setText("Acerca de");
        optmAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmAcercaActionPerformed(evt);
            }
        });
        helpMenu.add(optmAcerca);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnldEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnldEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void optmAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmAcercaActionPerformed
        // TODO add your handling code here:
      frmAcercaDeDialogo frmacerca=new frmAcercaDeDialogo(this, rootPaneCheckingEnabled);
      frmacerca.setVisible(true);
        
    }//GEN-LAST:event_optmAcercaActionPerformed

    private void optmCursoAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmCursoAcademicoActionPerformed
        // TODO add your handling code here:
        //frmCursoAcademico frmcursoaca=new frmCursoAcademico();
        //frmcursoaca.show();
//setVisible(true);

        frmInternoCursoAca frmcursoaca=null;

        if (!existeFormulario(frmcursoaca)){
            frmcursoaca=new frmInternoCursoAca();
            pnldEscritorio.add(frmcursoaca);
            
            frmcursoaca.show();
                 
       }
    }//GEN-LAST:event_optmCursoAcademicoActionPerformed

    private void optmAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmAlumnoActionPerformed
        
        // TODO add your handling code here:
        
       frmInternoAlumnos frmalum=null;
       
       if (!existeFormulario(frmalum)){
            frmalum=new frmInternoAlumnos();
            pnldEscritorio.add(frmalum);
            frmalum.show();
                 
       }
       
              
    }//GEN-LAST:event_optmAlumnoActionPerformed

    private void optmCursoAcademicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optmCursoAcademicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_optmCursoAcademicoMouseClicked

    private void optmCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmCursoActionPerformed
        // TODO add your handling code here:
        frmInternoCurso form=null;
       
        if (!existeFormulario(form)){
            form=new frmInternoCurso();
            pnldEscritorio.add(form);
            form.show();         
        }
        
    }//GEN-LAST:event_optmCursoActionPerformed

    private void optmUnidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optmUnidadesMouseClicked
        // TODO add your handling code here:
        frmFormularioEjemplo form=null;

        if (!existeFormulario(form)){
            form=new frmFormularioEjemplo();
            pnldEscritorio.add(form);
            form.show();
        }
    }//GEN-LAST:event_optmUnidadesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmMain().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenuCursoAcademico;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem optmAcerca;
    private javax.swing.JMenuItem optmAlumno;
    private javax.swing.JMenuItem optmCurso;
    private javax.swing.JMenuItem optmCursoAcademico;
    private javax.swing.JMenu optmUnidades;
    private javax.swing.JDesktopPane pnldEscritorio;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
